### ISSUE TITLE
GFM syntax: nested lists

### ISSUE THREAD

**Issue by sontono** [Rebilly/ReDoc#122]
GFM syntax lets to create nested lists by  indenting lines by two spaces, but they seems not to be correctly displayed in ReDoc, for example:
```json
"description": "Do following tasks:\n
- one\n
  - one.one\n
  - one.two\n"
```

**Comment by RomanGotsiy** [comment]
@sontono this is not valid json because of newlines in string literal (it is still for some reason parsed by the browser BUT trailing spaces are removed from each line).

To solve your issue remove newlines from json:

```json
"description": "Do following tasks:\n- one\n  - one.one\n  - one.two\n"
```

or use YAML:

```yaml
  description: |
    Do following tasks:
    - one
      - one.one
      - one.two
```
