### ISSUE TITLE
Incorrect string sample with `maxLength`

### ISSUE THREAD

**Issue by RomanGotsiy** [Rebilly/ReDoc#137]
![image](https://cloud.githubusercontent.com/assets/3975738/20090114/d06b569c-a593-11e6-8273-60a11ee1b041.png)

```yaml
Country:
  description: The Country refers to the [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). Two characters max.
  type: string
  maxLength: 2
```
