### ISSUE TITLE
How to set discriminator attribute for a header parameter? 

### ISSUE THREAD

**Issue by jenniferwang2000** [Rebilly/ReDoc#154]
There is a `version` parameter in header. I want to set discriminator for this field. For example, when this field is set `v1`, request body schema of v1 is shown. when this field is set to `v2`, request body schema of v2 is shown. 
I tried `discriminator`, swagger error prompted immediately.
I tried `x-extendedDiscriminator` as shown below, no swagger error, but the drop-down list is not shown in Redoc at all. 
```
      parameters:
        - name: version
          in: header
          required: false
          type: string
          description: ""
          x-extendedDiscriminator: version
```
If I set `x-extendedDiscriminator: version` in the request body schema, it works totally fine. But the fact is that `version` should be header parameter, not a field in request body. 

![image](https://cloud.githubusercontent.com/assets/20762285/20962107/efc04522-bca2-11e6-88d5-eb8f53c91446.png)

So how to achieve this, and do we support discriminator across schema? Thanks~
