### ISSUE TITLE
Do we have a way to remove the "Download " button on the top? Thanks~

### ISSUE THREAD

**Issue by jenniferwang2000** [Rebilly/ReDoc#180]

**Comment by RomanGotsiy** [comment]
@jenniferwang2000 there are no option for this.
Right now you can workaround it by adding the following `css`:

```css
.api-info-wrapper > p:first-of-type {
    display: none;
}
```
