### ISSUE TITLE
Schema: show type string with minLength 1 as "non-empty"

### ISSUE THREAD

**Issue by dolmen** [Rebilly/ReDoc#192]
With the following schema definition:
```yaml
name:
    type: string
    description: Name of the resource
    minLength: 1
```
The current rendering says: « >=1 characters »

It would be better for human consumption to specialize the case where `minLength` is `1` and `maxLength` is not set to show instead « non-empty ».
