### ISSUE TITLE
Sub category does not appear in Demo spec

### ISSUE THREAD

**Issue by kevprice83** [Rebilly/ReDoc#196]
I'm just testing this tool and so far it ticks all the boxes. I noticed that the sub category does not render in the demo [here](https://rebilly.github.io/ReDoc/). The animated GIF shows the ability to open a sub category and enter the necessary parameters. I am testing with the sample petstore spec on my site and the same issue occurs.

Am I missing something very obvious or is there a dependency I'm not including?

I'm referencing the library via CDN.

**Comment by RomanGotsiy** [comment]
The gif was taken from modified locally petstore spec. It is not committed to demo.

**Comment by kevprice83** [comment]
So what is necessary to create the subcategory fields? SwaggerUI for example interprets on the first operation a body parameter and produces a text area. Is some extra parameter required to do the same for ReDoc?

**Comment by RomanGotsiy** [comment]
In ReDoc we try to document request and response payloads as much as possible. So when SwaggerUI just renders a text area we render payload recursively with all the metadata.

Payload is generated based on [SchemaObject](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object) from OpenAPI spec which is limited version of [JsonSchema Draft 4](http://json-schema.org/)

Subproperties in JSON Schema are documented with `properties` keyword. If we take `Category` definition from demo it may look like this:
```yaml
Category:
  type: object
  properties:
    subcategory:
      type: object # <- set type of field to object
      properties: # <- here we document subproperties
        name:
          type: string
    id:
      description: Category ID
      type: string
    name:
      description: Category name
      type: string
      minLength: 1
```

I will update demo spec in the upcoming release.
Let me know if you have any other questions
