### ISSUE TITLE
Schema rendering: improve type string with minLength == maxLength

### ISSUE THREAD

**Issue by dolmen** [Rebilly/ReDoc#212]
```yaml
type: string
minLength: 22
maxLength: 22
```
should be rendered like this: `exactly 22 characters` (or a variation)

Currently it is rendered as `[22..22] characters` which is less readable for humans. 

This is related to #192. Both should be fixed together.
