### ISSUE TITLE
Discriminator dropdown in request body, removes parent type

### ISSUE THREAD

**Issue by ChrisTitos** [Rebilly/ReDoc#220]
Hi,

Excuse the confusing title, it's difficult to explain in one sentence :)

I have a definition that has a discriminator like this:

```
Message:
    type: object
    discriminator: msg_type
    properties:
      msg_type:
        type: string
        enum: [Message, Alert, Event, Question, DynamicSupply, Issue]
```

Alert, Event, Question etc are all subclasses of Message, but in my case Message is not "abstract" if you know what I mean, it's a valid object, hence it's one of the enum values. However the dropdown removes Message and only shows the subclasses with the first one automatically selected:

![afbeelding](https://cloud.githubusercontent.com/assets/2377451/23548286/0b40b2c6-0007-11e7-8c9e-966fec378005.png)

This is confusing because now you cannot see that Message is a valid type with less proprties
