### ISSUE TITLE
Inline post body with parameters results in warning 

### ISSUE THREAD

**Issue by asikkema** [Rebilly/ReDoc#254]
When creating a post with in inline body a warning around types shows up:
```
No "type" specified at "/paths/~1route/post/parameters/0/schema". Automatically detected: "object"
```

to reproduce:
```yaml
 /route:
    post:
      summary: Get the road information on the given route.
      description: |
        Uses a mapmatching algorithm to determine the selected roads for the given route.
        Returns the requested info for those roads at the current time.
      parameters:
        - name: location
          in: body
          type: object
          required: true
          schema:
            properties:
              polyline:
                type: string
                format: polyline
                description: |
                  [Google encoded polyline](https://developers.google.com/maps/documentation/utilities/polylinealgorithm)
                example:
                  iym|Hgtw]D?qA[sCw@}AWu@tK{Cp]QrEGhDDfCEBGR?ToExBsJhFa@d@GLKFi@vBKV}AmB]u@m@aD{AcK?ME?s@WQAsDtBbA`H}DrBZxBPGRbAt@e@CU
            required:
              - polyline
```

The simple workaround is to make the inline object definition into a $ref.

**Comment by agboom** [comment]
I ran into a similar problem, where I specified the type in in a `$ref`. 

The configuration below results in a warning `No "type" specified at "/paths/~1position/get/parameters/0". Automatically detected: "object"`.

```yaml
      parameters:
        - name: lat
          in: query
          schema:
            $ref: '#/definitions/Latitude'
          description: Latitude of the position.
          required: true

definitions:
  Latitude:
    type: number
    format: double
```

When `type` is defined directly in `parameters`, this warning does not occur. I can imagine that when someone creates a `$ref` with a `type` that it should be picked up by the schema.

**Comment by RomanGotsiy** [comment]
@asikkema the warning message provides the exact issue: you don't have type specified at `/paths/~1route/post/parameters/0/schema`:

```yaml
schema:
     type: object # <- add `type: object` here
     properties:
          polyline:
               type: string
```
According to Swagger spec which uses JSON Schema Draft 4 underneath, if you do not specify `type:object` in the schema, it will successfully validate for example any string, number, boolean.

You can check it yourself on https://jsonschemalint.com
If you write simple schema like following:

```json
{
  "properties": {
    "a": {
      "type": "string"
    }
  }
}
```

![image](https://cloud.githubusercontent.com/assets/3975738/25226102/5e96faa8-25cc-11e7-85ae-bc7210846dcc.png)

That's why ReDoc shows the warning.
You can disable warnings in UI by using option [`suppress-warnings`](https://github.com/Rebilly/ReDoc#redoc-tag-attributes).

@agboom your spec is invalid according to the swagger. If `in` is `query` you must specify `type`. Check details [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object)
