### ISSUE TITLE
Doesn't display enum with single value

### ISSUE THREAD

**Issue by Sorix** [Rebilly/ReDoc#284]
ReDoc doesn't display valid values if enum consists only from 1 value. It may be used for development or future release purposes (we will add values later).

**Example**
```yaml
  /client/{os}:
    get:
      parameters:
      - name: os
        in: path
        description: client's operating system
        required: true
        type: string
        enum:
          - android
```

There will be no "Valid values" section, but if we add one more enum it will be shown.
