### ISSUE TITLE
Dates need quotes in YAML and they shouldn't

### ISSUE THREAD

**Issue by philsturgeon** [Rebilly/ReDoc#295]
Hey! A bug appeared today. I had this property defined:

``` yaml
  type: object
  properties:
    begins_at:
      description: ISO 8601 date and time the office hold starts.
      type: string
      format: dateTime
      example: 2016-08-04T18:53:38.297Z
```

The output looked like this:

<img width="248" alt="screen shot 2017-07-10 at 1 02 16 pm" src="https://user-images.githubusercontent.com/67381/28030163-9c6b9792-6570-11e7-8552-abfcc8318be8.png">

Notice the example is an empty object! 

I wrapped the example in doublequotes and it worked, but I shouldn't need to. The original was valid YAML (according to http://www.yamllint.com/ anyhow):

<img width="702" alt="screen shot 2017-07-10 at 1 05 43 pm" src="https://user-images.githubusercontent.com/67381/28030193-baf2120e-6570-11e7-8890-379ade87c3db.png">

I have a temporary solution so I'm fine here, but could you take a look into this at some point?

**Comment by philsturgeon** [comment]
Just experienced the same thing with this field:

``` yaml
    date:
      type: string
      format: date
      example: "2016-08-06"
```

I thought it might be related to `:` in the timestamp but seems like `-`'s trip it too.
