### ISSUE TITLE
Header example values

### ISSUE THREAD

**Issue by philsturgeon** [Rebilly/ReDoc#297]
Seing as Swagger does not seem to support example values for securityDefinitions, I am defining an `exampleToken` header parameter and referencing it in every endpoint that requires the token.

```yaml
parameters:
  exampleToken:
    name: Authorization
    in: header
    required: true
    type: string
    x-example: "Token=exampletoken1"
```

I'm using that x-example because I'm using Dredd which needs examples for things to work, and ReDoc supports this too - which is handy!

Right now the headers are referenced as existing, but no example shows up:

<img width="1157" alt="screen shot 2017-07-10 at 6 30 45 pm" src="https://user-images.githubusercontent.com/67381/28043214-df406484-659e-11e7-9497-1e58acd59313.png">

Apiary has a little "Headers" section above the request body:

<img width="295" alt="screen shot 2017-07-10 at 6 36 44 pm" src="https://user-images.githubusercontent.com/67381/28043185-c57beaf0-659e-11e7-80a3-bf90f1165be9.png">

If this could be added to ReDoc, it would be so damn handy! 

Ofc for now I've got it hacked into the description, which is fine: 

<img width="608" alt="screen shot 2017-07-10 at 6 38 43 pm" src="https://user-images.githubusercontent.com/67381/28043254-0c0207ca-659f-11e7-8c2e-822244712810.png">
