### ISSUE TITLE
Readonly parameters are not visible in the UI

### ISSUE THREAD

**Issue by caramanico** [Rebilly/ReDoc#299]
In my .yaml I have several read-only parameters (body params) and they are not shown in the UI. Is there any way to show them?

For example:
```
auth.AuthWithNonceBodyRequest:
    type: "object"
    properties:
      device_id:
        type: "string"
        readOnly: true
```

Thanks in advance,
Franco.-
