### ISSUE TITLE
x-code-samples with Swagger Annotations

### ISSUE THREAD

**Issue by hugol1ma** [Rebilly/ReDoc#376]
Hi,

I have one problem for x-code-samples with Swagger Annotations. I can generate x-code-sample, but accept only one object... 
No attempt worked with annotations

Example:
Java Class Rest:
```java
...
@ApiOperation(value = "Find person by id",
    extensions = @Extension( name = "code-samples", properties = {
        @ExtensionProperty(name = "source", value = "console.log('Hello World');"),
        @ExtensionProperty(name = "lang", value = "JavaScript")
    })
)
...
```

Automatic generate file:
```yaml
paths:
  /people/{id}:
    get:
      summary: "Find person by id"
      description: ""
      ...
      x-code-samples:
        lang: "JavaScript"
        source: "console.log('Hello World');"
```
_Code above does not work_

Another attempt
```java
...
@ApiOperation(value = "Find person by id",
    extensions = @Extension( name = "code-samples", properties = {
        @ExtensionProperty(name = "source", value = "console.log('Hello World');"),
        @ExtensionProperty(name = "lang", value = "JavaScript"),
        @ExtensionProperty(name = "source", value = "System.out.println('Hello World');"),
        @ExtensionProperty(name = "lang", value = "Java")
    })
)
...
```

Automatic generate file:
```yaml
paths:
  /people/{id}:
    get:
      summary: "Find person by id"
      description: ""
      ...
      x-code-samples:
        lang: "Java"
        source: "System.out.println('Hello World');"
```
_The above code also does not work_

Attribute x-code-sample only work if i get generated file and adding `-` before `lang`:
```yaml
paths:
  /people/{id}:
    get:
      summary: "Find person by id"
      description: ""
      ...
      x-code-samples:
      - lang: "JavaScript"
        source: "console.log('Hello World');"
```
I could not find how to do x-code-sample list by annotations
Have any suggestion ?

**Comment by RomanGotsiy** [comment]
@hugol1ma I've never used swagger annotations in Java but I've checked the docs and it seems they don't support array values for extension values.

An array is expected in ReDoc to be able to specify samples order.

I recomend you to use the following syntax:

```java
...
@ApiOperation(value = "Find person by id",
    extensions = @Extension( name = "my-code-samples", properties = {
        @ExtensionProperty(name = "JavaScript", value = "console.log('Hello World');"),
        @ExtensionProperty(name = "Java", value = "System.out.println('Hello World');"),
    })
)
...
```

which will generate you:
```yaml
paths:
  /people/{id}:
    get:
      summary: "Find person by id"
      description: ""
      ...
      x-my-code-samples:
        JavaScript: "console.log('Hello World');"
        Java: "System.out.println('Hello World');"
```
and then just postprocess resulting spec either directly in Java (I'm don't know how to do this, I tried to google but Java is soo scary 😱 but I think it can be done using some `CustomObjectMapper` or something like that) or later with some script e.g. in JavaScript:

```js
function postProcess(spec) {
  for (let key in spec.paths) {
  let path = spec.paths[key];
    for (let verb in path) {
      if (verb === 'parameter' || verb.startsWith('x-')) continue; // filter non-verbs
      let operation = path[verb];
      operation['x-code-samples'] = Object.keys(operation['x-my-code-samples']).map(lang => {
        return { lang: lang, source: operation['x-my-code-samples'][lang] }
      });
    }
  }
}
```

Closing this issue, but feel free to continue the discussion here!
