### ISSUE TITLE
Example with null

### ISSUE THREAD

**Issue by juanitobebe** [Rebilly/ReDoc#415]
Hello,

I have a problem expressing in an example that a property should be null, see:
![image](https://user-images.githubusercontent.com/10404960/36179979-2c68e8e4-10e4-11e8-8f48-2e0c5d0186ca.png)

In the yaml the property is defined as:
```
          previous_page:
             type: number
             x-nullable: true
             description: 'The previous page number.This value is null if there is no previous page to show.'
             example: null
```

We thought that including `x-nullable: true` should be enough.

Is there a workaround for this when using Swagger 2.0 and ReDoc 1.2?

I'll be glad to make that small change in the example renderer if it's needed, I just need someone to shed some light on me.
