### ISSUE TITLE
Small iffy thing about using tags

### ISSUE THREAD

**Issue by unional** [Rebilly/ReDoc#431]
```yaml
x-tagGroups:
  - name: General
    tags:
     - Foo
tags:
  - name: Foo
paths:
  /abc:
    get:
      tags:
        - Foo
  /foo:
    get:
      tags:
        - Foo
```

With the above spec, Redoc will generate A side manual of `Foo` with two get methods: `/abc` and `/foo`

The order of the methods (`/abc -> /foo` vs `/foo -> /abc`) depends on the parsing order of the object `paths`.

This is a bit iffy because the property order of an object (`paths` in this case) is not guaranteed.

Just want to point this out and see if there are any thoughts in dealing with it. 🌷
