### ISSUE TITLE
Support for remote references in OpenAPI 3.0

### ISSUE THREAD

**Issue by SensibleWood** [Rebilly/ReDoc#452]
I've written an OpenAPI 3.0 specification which includes remote references in the following styleee:

```
    ObjectName:
      type: object
      required:
      - callbackUrl
      - payload
      properties:
        callbackUrl:
          type: string
        payload:
          $ref: 'http://localhost:8000/payload.json#/components/schemas/Payload'
```

However, at the very least the distributed ReDoc library doesn't like these references - or a least fails to interpret them:

```
Something went wrong...
Invalid reference token: properties
Stack trace
Error: Invalid reference token: properties
    at Function.o.get (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:92:14896)
    at e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:92:22910)
    at n.sampleArray (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:92:19136)
    at e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:92:23538)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:92:21037
    at Array.forEach (<anonymous>)
    at n.sampleObject (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:92:20997)
    at e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:92:23538)
    at e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:92:22951)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:92:21037

ReDoc Version: 2.0.0-alpha.17 
Commit: de177a0
```

No issues when loading an OpenAPI spec sans the remote references. 

Incidentally I don't think this is a CORS issue - I can see the remote files have been successfully retrieved in the network console in Chrome.

Help on this would be mucho appreciated.
