### ISSUE TITLE
1.x: minimum and maximum does not work for type float

### ISSUE THREAD

**Issue by unional** [Rebilly/ReDoc#472]
```yaml
      geo-location:
        type: object
        properties:
          latitude:
            type: float
            minimum: -90
            maximum: 90
            description: latitude coordinate
          longitude:
            type: float
            minimum: -180
            maximum: 180
            description: longitude coordinate
```
This does not render the range:
![image](https://user-images.githubusercontent.com/3254987/39226925-5b681504-480a-11e8-9c8b-b9964f8c3501.png)

If I change the type from `float` to `integer`, it works:
![image](https://user-images.githubusercontent.com/3254987/39226933-6efd9ed6-480a-11e8-9cfe-462c73c74491.png)
