### ISSUE TITLE
feature request: configuration to hide search box

### ISSUE THREAD

**Issue by imnotashrimp** [Rebilly/ReDoc#498]
Feature request:

I'd like a way to hide the search box. Today, I work around this by setting this css:

```css
div[role=search] {
  display: none;
}
```
_But..._ I'd love to be able to configure the search away.

Thanks for an awesome project!
