### ISSUE TITLE
Discriminator field does not change upon selecting different models in request sample

### ISSUE THREAD

**Issue by debri174** [Rebilly/ReDoc#524]
I'm running into a bug with the discriminator field in Request Samples. When I click on the various models the value in the discriminator field does not change. 

Here is a portion of my spec that shows the discriminator setup:

```
pageelementscommon:
    type: object
    discriminator: type
    properties:
      id:
        type: integer
        description: Question ID
        readOnly: true
      type:
        type: string
        description: Element type used to determine schema to post/returned
        enum:
        - cascadingdropdown
        - checkboxes
        - contactform
        - contsum
        - customgroup
        - customtable
        - date
        - dropdown
        - email
        - essay
        - fileupload
        - gridcheckboxes
        - griddropdown
        - gridradiobutton
        - gridstars
        - gridtextbox
        - imagemulti
        - imagesingle
        - instructions
        - likert
        - listdropdown
        - listtextbox
        - nps
        - number
        - percent
        - radiobuttons
        - rankdragdrop
        - rankgrid
        - signature
        - slider
        - slidermulti
        - textbox
        - customscriptaction
        - hiddenvalueaction
        - javascriptaction
        - loginaction
        - pagetimeraction
        - percentbranchaction
        - quizscoreaction
        - recaptchaaction
        - resultschartaction
        - reviewaction
        - sectionnavaction
        - emailaction
        - socialmediaaction
        - urlredirectaction
        - webhookaction
        - video
        - audio
```

Here's a demo of the issue:

![request-sample-discrim-bug](https://user-images.githubusercontent.com/32558006/40890135-6a4e1166-672e-11e8-9787-15ddec75f689.gif)

This is problematic because, as you can see, the subsequent fields are often the same for the various models so the end user might think that the examples are not changing even though they are. 

Thanks for such a great tool!
