### ISSUE TITLE
Support multiple oneOf calls that are not nested

### ISSUE THREAD

**Issue by viralanomaly** [Rebilly/ReDoc#528]
Right now, the only way to have my request show a second, unrelated oneOf selection is to do this:
```
MyObject:
  allOf:
    - oneOf:
        - allOf:
           - $ref: 'RefToChoice1Option1'
           - oneOf:
              - $ref: 'RefToChoice2Option1'
              - $ref: 'RefToChoice2Option2'
        - allOf:
           - $ref: 'RefToChoice1Option2'
           - oneOf:
              - $ref: 'RefToChoice2Option1'
              - $ref: 'RefToChoice2Option2'
```

I would prefer to be able to do this:
```
MyObject:
  allOf:
    - oneOf:
       - $ref: 'RefToChoice1Option1'
       - $ref: 'RefToChoice1Option2'
    - oneOf:
       - $ref: 'RefToChoice2Option1'
       - $ref: 'RefToChoice2Option2'
