### ISSUE TITLE
type: boolean and default: false does not render default value

### ISSUE THREAD

**Issue by tyteen4a03** [Rebilly/ReDoc#544]
Example, within a Schema:

```
        TruthyDefault:
          type: boolean
          default: true
        FalsyDefault:
          type: boolean
          default: false
```

The `TruthyDefault` parameter will render `default: true`, but `FalsyDefault` won't render a default at all.
