### ISSUE TITLE
Support for JWT

### ISSUE THREAD

**Issue by rrjanbiah** [Rebilly/ReDoc#574]
I'm sorry, if this is not appropriate to post here...

Can someone please share some idea on how to handle JWT protected endpoint with ReDoc. Currently, it displays documentation. But, how to make the API 'play ground' working? Or, how to setup headers? Possibility to do that along with CDN version would be awesome. TIA

**Comment by rrjanbiah** [comment]
I'm sorry.. looks like I completely misunderstood about the 'play ground' part. ReDoc doesn't have that feature.

I also, found that by converting Swagger 2.0 spec to OpenAPI 3.0 spec and adding below securitySchemes, adds up API related information:

```
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  
```

So, this ticket can be closed.
