### ISSUE TITLE
Add icons in menu representing particular HTTP verb

### ISSUE THREAD

**Issue by IvanGoncharov** [Rebilly/ReDoc#61]
Something similar to this:
![image](https://cloud.githubusercontent.com/assets/8336157/16419467/855ca782-3d56-11e6-9209-323aad5ed580.png)

**Comment by SebastianStehle** [comment]
I am not a fan of it. I think this is a technical detail that should stay on the right side.

**Comment by RomanGotsiy** [comment]
Implemented via https://github.com/Rebilly/ReDoc/commit/92eec25

@SebastianStehle if you don't like it you can hide it using css. Let me know if you need assistance.

**Comment by avkonst** [comment]
The documentation on how to hide it would be good to have.

**Comment by RomanGotsiy** [comment]
@avkonst you can just hide it with `css` e.g.:

```css
redoc .operation-type {
    opacity: 0;
}
```

or 

```css
redoc .operation-type {
    display: none !important;
}
```
