### ISSUE TITLE
Incorrect display of nested oneOf properties

### ISSUE THREAD

**Issue by fredriklengstrand** [Rebilly/ReDoc#618]
When you have nested oneOf properties the top level type for the property looks incorrect:

![screen shot 2018-08-23 at 11 04 24](https://user-images.githubusercontent.com/10126466/44516077-68fcd100-a6c4-11e8-968a-fbc0872aaf89.png)

Shouldn't it be "Array of string or integer" or "string" in this case?

Here is a sample property:

```
test:
  oneOf:
    - type: array
      items:
        oneOf:
          - type: string
          - type: integer
    - type: string
```
