### ISSUE TITLE
WARNING: No "type" specified

### ISSUE THREAD

**Issue by mes3yd** [Rebilly/ReDoc#653]
This happens when referencing a path parameter. It expects a type to be on the parameter itself and not as a child of schema:

Works:
```yaml
service_id:
  name: service_id
  in: path
  required: true
  type: integer
```
Doesn't work:
```yaml
service_id:
  name: service_id
  in: path
  required: true
  schema:
    type: integer
```

The reference can be in another file or simply `#/components/parameters/service_id`.
Since it recognizes no type and defaults to object, on cannot fill in any parameters to test.
