### ISSUE TITLE
2.0.0-alpha.40 broke markdown formatting in/after HTML

### ISSUE THREAD

**Issue by cmeeren** [Rebilly/ReDoc#684]
Writing ``<p>`test`</p>`` works fine in 2.0.0-alpha.39, but has not worked since 2.0.0-alpha.40.

The same also goes for some headings after HTML. For example, the following renders fine in 39, but not 40 - in the latter, `### Relationships` is rendered as is, not as a heading:

```yaml
tags:
  - name: confirmationCode
    description: >
      ## confirmationCode
    
      Used for operations requiring 2FA.
    
      ### Attributes
    
      <p>test</p>
      
      ### Relationships
      
      None.
```

**Comment by RomanGotsiy** [comment]
This is caused by updating to the latest version of [`marked.js`](https://github.com/markedjs/marked/blob/master/lib/marked.js) which is used as a Markdown parser in ReDoc.
The latest version is more CommonMark-compatible and states that markdown should be CommonMark ([link](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#rich-text-formatting)):

![image](https://user-images.githubusercontent.com/3975738/47290647-23e41500-d609-11e8-887f-d151e4baca01.png)


So the first issue you reported:

```
<p>`test`</p>
```

is rendered absolutelly correct according to CommonMark rules: [CommonMark Playground link](https://spec.commonmark.org/dingus/?text=%3Cp%3E%60test%60%3C%2Fp%3E)

In the second example you're using Folded Block Scalar (`>`) in yaml which removes any extra-newlines, so your md-snippet is equal to the following:

```
## confirmationCode
Used for operations requiring 2FA.
### Attributes
<p>test</p>
### Relationships
None.
```

which is rendered correctly by ReDoc too according to Commonmark: [CommonMark Playground link](https://spec.commonmark.org/dingus/?text=%23%23%20confirmationCode%0AUsed%20for%20operations%20requiring%202FA.%0A%23%23%23%20Attributes%0A%3Cp%3Etest%3C%2Fp%3E%0A%23%23%23%20Relationships%0ANone.)

You can fix it by using `: |` in your yaml:

```yaml
tags:
  - name: confirmationCode
    description: | # <---- here
      ## confirmationCode
    
      Used for operations requiring 2FA.
    
      ### Attributes
    
      <p>test</p>
      
      ### Relationships
      
      None.
```

Closing the issue. ReDoc works correctly.
Feel free to continue discussion here though.
