### ISSUE TITLE
Support for tuple arrays

### ISSUE THREAD

**Issue by IvanGoncharov** [Rebilly/ReDoc#69]
represent schemas like this:

``` yaml
type: array
items:
  - type: string
  - type: number
```

\+ mark some items as required based on value of `minItems`.
