### ISSUE TITLE
oneOf cases referencing external files are empty and recursive from the third case

### ISSUE THREAD

**Issue by cmeeren** [Rebilly/ReDoc#723]
I have the following response:

```yaml
application/json:
  schema:
    oneOf:
      - $ref: 'errors.yaml#/SignInNoValidMobile'
      - $ref: 'errors.yaml#/SmsSendingFailed'
      - $ref: 'errors.yaml#/SignInInvalidCredentials'
```

In `errors.yaml` I have defined the three types. They are, for all intents and purposes, identical. (I have even tried copying them from one another and only edited the name.)

It seems that all `oneOf` cases from the third element are rendered as empty and recursive:

![image](https://user-images.githubusercontent.com/7766733/48843430-5cf1df80-ed97-11e8-849d-6c7018d054b5.png)

The first two work fine, but no matter which order I put them in, the third one is rendered as shown above. The same goes for a fourth element that I tried adding.
