### ISSUE TITLE
Add description to TagGroup

### ISSUE THREAD

**Issue by unional** [Rebilly/ReDoc#760]
...would be nice. 🌷

**Comment by viralanomaly** [comment]
This would be really really nice.

**Comment by styvas** [comment]
This isn't exactly what you want, but I found a workaround by creating an empty tag in the tag: section at the root level, and then assigned it as the first tag in the group. Because I can provide a description for the basic tag: but not for x-TagGroups tags, it works as long as it's been named appropriately (and if you wanted each one called "introudction" or "Overview', etc., but need this repeated, give it a unique name and then use x-DisplayName to assign the common label.

`tags:
  - name: System Admin Lookups Overview
    x-displayName: "Section Overview"
    description: |-
      An vel posse accommodare! Nobis utinam appareat vel ne, id quaerendum comprehensam interpretaris mea. Has ei vitae legere detracto, vix an vitae quaeque fabellas. An solum sonet aperiam nec! Erat petentium mel eu, quis altera incorrupte at eam.

x-tagGroups:
  - name: System Admin Lookups
    tags:
      - System Admin Lookups Overview
      - Relationships
      - Countries
...
`

**Comment by codyaray** [comment]
I like @styvas workaround. The only challenge is that I would prefer the long title ("System Admin Lookups Overview") in the main body but the short "Section Overview" text in the left nav. For now I've just used the long-form in both places, of the form "Overview: System Admin Lookups" so that it shows a bit better in the left nav.

**Comment by damianobarbati** [comment]
I'm not sure what's supposed to happen, I don't see anything rendered other than the usual entry in the navbar.

Is this supposed to create an heading in the main description AND the nav entry clickable to it?
I was trying something like this:
```yml
tags:
  - name: API reference
    x-displayName: API reference
    description: |-
      All API endpoints explained hereafter.

x-tagGroups:
    - name: API reference
      tags:
        - Auth
        - Translate
```
