### ISSUE TITLE
Matrix parameter support

### ISSUE THREAD

**Issue by marbon** [Rebilly/ReDoc#761]
Since v2 matrix parameters (https://www.w3.org/DesignIssues/MatrixURIs.html) are part of the OpenAPI Spec. We use them in our API and would be happy about a Redoc support.
```
parameters:
  - name: id
    in: path
    required: true
    style: matrix
    schema:
      type: string
```
