### ISSUE TITLE
Using AllOf to inherit an array doesn't work

### ISSUE THREAD

**Issue by GuillaumeToubache** [Rebilly/ReDoc#791]
Trying to inherit something that isn't an array will work fine, so will inheriting an object that contains an array, but when directly inheriting an array Redoc is not be able to consume it even though it works fine in the swagger editor.

```
Example:
    allOf:
      - $ref: '#/definitions/BaseApiResponse'
      - type: object
        required:
          - Data
        properties:
          Data:
            type: array
            items:
              $ref: "#/definitions/MerchantInventory"
```
![image](https://user-images.githubusercontent.com/25306822/51543235-1a965e80-1e2b-11e9-9a66-6560edcfdfbf.png)
![image](https://user-images.githubusercontent.com/25306822/51543252-26822080-1e2b-11e9-9572-829c6d5c2908.png)
![image](https://user-images.githubusercontent.com/25306822/51543268-2eda5b80-1e2b-11e9-8e0e-cb58cfb96034.png)

**Comment by RomanGotsiy** [comment]
Could you send `BaseApiResponse` and `MerchantInventory`?

I can't reproduce it.

**Comment by GuillaumeToubache** [comment]
Sure, here you go.
```
  BaseApiResponse: #would normally be used in inheritance, but redoc can't handle it
    type: object
    properties:
      StatusCode:
        type: integer
        format: int32
      Message:
        type: string
      ErrorMessage:
        type: string
      Data:
        type: object
        default: null
```
```
  MerchantInventory:
    type: object
    properties:
      StoreId:
        type: integer
        format: int32
      InventoryQuantity:
        type: integer
        format: int32
      LiquidationQuantity:
        type: integer
        format: int32
```
