### ISSUE TITLE
Escaped double-quote \" is not shown as escaped in example

### ISSUE THREAD

**Issue by exoego** [Rebilly/ReDoc#822]
* Tested on https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.2/bundles/redoc.standalone.js

My schema has a string field which stores JSON template like

```yml
body:
    type: string
    example: "{\"message\": \"test\"}"
```

or

```yml
body:
    type: string
    example: '{"message": "test"}'
```

But both of them are shown like

![image](https://user-images.githubusercontent.com/127635/53389360-55fbee00-39d2-11e9-83fe-1d6549acf0ef.png)

where double-quote `"` is shown directly, therefore the response exmple looks like broken.

I think doubel-quote are escaped and shown like `\"`.
