### ISSUE TITLE
Suggestion: extra information

### ISSUE THREAD

**Issue by Zedebeus** [Rebilly/ReDoc#837]
Extra information places would be useful to add more descriptions to operation and tag level. It would practical if this is available already in the source file too. 

An possible solution is to use a new vendor extension. For example: 
```yaml
x-extraInfo:
  - name: Info1
    descrition: |
      Markdown Info 1
  - name: Info2
    descrition: |
      Markdown Info 2
```
In my mind this information would be avilable at the end of the section collapsible way. These elements would be closed initially.
