### ISSUE TITLE
Capitalize first letter of the "in" value in apiKey Security scheme

### ISSUE THREAD

**Issue by Alexgmin** [Rebilly/ReDoc#880]
This definition:
```yaml
  securitySchemes:
    Signature:
      description: foo
      name: Authorization
      type: apiKey
      in: header
```
Results in this:
![image](https://user-images.githubusercontent.com/8340441/55409445-5acc3880-5562-11e9-90f5-c172e77073da.png)

`in: Header` instead of `in: header` solves the problem, but `Header` is an invalid value according to the spec.
