### ISSUE TITLE
Update fields that are rendered put/post

### ISSUE THREAD

**Issue by tatiana-perry** [Rebilly/ReDoc#898]
In open API 3.0, you can now mark a field as being required for a PUT or POST only without needing to break it out into a new model or request. This was you can use one model and just mark what is required for a PUT or POST request. 

Example:

```
    MetafieldBase:
      type: object
      description: Common Metafield properties.
      title: Metafield
      properties:
        id:
          type: integer
          description: Unique ID of the *Metafield*. Read-Only.
          example: 6
          readOnly: true
        permission_set:
          type: string
          description: >
            Determines whether the field is completely private to the app that
            owns the field (`app_only`), or visible to other API consumers
            (`read`), or completely open for reading and writing to other apps
            (`write`). Required for POST.
          enum:
            - app_only
            - read
            - write
          required:
            - post
...
```
vs 
```
    MetafieldBase:
      type: object
      description: Common Metafield properties.
      title: Metafield
      properties:
        id:
          type: integer
          description: Unique ID of the *Metafield*. Read-Only.
          example: 6
          readOnly: true
        permission_set:
          type: string
          description: >
            Determines whether the field is completely private to the app that
            owns the field (`app_only`), or visible to other API consumers
            (`read`), or completely open for reading and writing to other apps
            (`write`). Required for POST.
          enum:
            - app_only
            - read
            - write
     required:
         - permission_set

```

<img width="515" alt="Screen Shot 2019-04-23 at 3 28 11 PM" src="https://user-images.githubusercontent.com/16635677/56613526-6e584580-65dc-11e9-851c-9702dfd89c51.png">
