### ISSUE TITLE
Redoc side bar is moving on scroll when using a fixed navbar

### ISSUE THREAD

**Issue by LogX7** [Rebilly/ReDoc#901]
so i'm trying to setup redoc in my web application, and i have a fixed navbar

my problem is that when i scroll the redoc sidebar and code area scroll up too, instead of staying fixed,

here's an example of my code:

```css
body {
    margin: 0;
    padding: 0;
}
.navbar {
    position: fixed;
    top: 0;
    left: 0;
    /* z-index: 2; */
    background: red;
    width: 100%;
    height: 50px;
}

.content {
    margin-top: 50px;
}
```

```html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="style.css">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">
</head>
<body>
	<div class="navbar"></div>
	<div class="content">
		<redoc spec-url='https://raw.githubusercontent.com/LogX7/MindrDocs/master/api.yml'></redoc>
		<script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"></script>
	</div>
</body>
</html>
```
