### ISSUE TITLE
cURL sample has bad CSS styles

### ISSUE THREAD

**Issue by antonkomarev** [Rebilly/ReDoc#904]
I've added x-code-samples with `lang: "cURL"` and here is what I've got.

![Screenshot from 2019-05-06 00-06-32](https://user-images.githubusercontent.com/1849174/57200313-30bbcb00-6f93-11e9-83ec-d656e072a78c.png)

**Comment by RomanGotsiy** [comment]
Could you create a minimal reproducible sample or share your set up? I can't reproduce it on my side.

**Comment by antonkomarev** [comment]
Ah, sorry, I've missed the fact that bootstrap CSS overrides `pre` tag color:
```css
pre {
    display: block;
    font-size: 87.5%;
    color: #212529;
}
```
