### ISSUE TITLE
Is there a way to prevent escaping of '"'s in examples?

### ISSUE THREAD

**Issue by rcrooks** [Rebilly/ReDoc#918]
Is there any way to get round the escaping of double-quotes in examples?
For instance:
```
example: >-
  {
    "vod_jobs": [
      {
        "jvod_id": "62989518f9294e19b2f7e184e8141d72",
        "label": "first 30 secs of live job"
      }
    ],
    "live_job_id": "3ae7fa89943f4a96aa273fbbf175d527"
  }```

is rendered as:

```"{
  \"vod_jobs\": [
    {
      \"jvod_id\": \"62989518f9294e19b2f7e184e8141d72\",
      \"label\": \"first 30 secs of live job\"
    }
  ],
  \"live_job_id\": \"3ae7fa89943f4a96aa273fbbf175d527\"
}"```

Tried everything I can think of, but can't get rid of the "\"s

**Comment by RomanGotsiy** [comment]
What is your example mime type? Could you share the whole spec (or minimal reproducible sample) or at least the corresponding operation spec.

**Comment by RomanGotsiy** [comment]
Ah, well your example is a string `>-` in yaml means string value.

Change to:

```yaml
example: {
  "vod_jobs": [
    {
      "jvod_id": "62989518f9294e19b2f7e184e8141d72",
      "label": "first 30 secs of live job"
    }
  ],
  "live_job_id": "3ae7fa89943f4a96aa273fbbf175d527"
}
```
